package com.test.repository;

import com.test.entity.Table2;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface Table2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    int insert(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    int insertSelective(Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    Table2 selectByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    int updateByPrimaryKeySelective(@Param("record") Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    int updateByPrimaryKey(@Param("record") Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    Table2 selectOne(@Param("record") Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    List<Table2> selectList(@Param("record") Table2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table2
     *
     * @mbg.generated Wed May 08 16:16:17 CST 2019
     */
    int updateByPrimaryKeySelectiveLock(@Param("record") Table2 record);
}