package com.test.auth.entity;

import java.util.Date;

public class SysGroupType {
    /**
     * ID
     */
    private Long id;

    /**
     * 组织类型code
     */
    private String code;

    /**
     * 组织类型名称
     */
    private String name;

    /**
     * 
     */
    private Date createTime;

    /**
     * 
     */
    private Date updateTime;

    /**
     * 备注
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_type.id
     *
     * @return the value of sys_group_type.id
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_type.id
     *
     * @param id the value for sys_group_type.id
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_type.code
     *
     * @return the value of sys_group_type.code
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_type.code
     *
     * @param code the value for sys_group_type.code
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_type.name
     *
     * @return the value of sys_group_type.name
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_type.name
     *
     * @param name the value for sys_group_type.name
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_type.create_time
     *
     * @return the value of sys_group_type.create_time
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_type.create_time
     *
     * @param createTime the value for sys_group_type.create_time
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_type.update_time
     *
     * @return the value of sys_group_type.update_time
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_type.update_time
     *
     * @param updateTime the value for sys_group_type.update_time
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_type.remark
     *
     * @return the value of sys_group_type.remark
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_type.remark
     *
     * @param remark the value for sys_group_type.remark
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}