package com.test.auth.entity;

import java.util.Date;

public class SysGroup {
    /**
     * ID
     */
    private Long id;

    /**
     * 组织code
     */
    private String groupCode;

    /**
     * 组织名称
     */
    private String groupName;

    /**
     * 
     */
    private Long groupTypeId;

    /**
     * 上级组织
     */
    private Long parentId;

    /**
     * 
     */
    private Date createTime;

    /**
     * 
     */
    private Date updateTime;

    /**
     * 备注
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.id
     *
     * @return the value of sys_group.id
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.id
     *
     * @param id the value for sys_group.id
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.group_code
     *
     * @return the value of sys_group.group_code
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.group_code
     *
     * @param groupCode the value for sys_group.group_code
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.group_name
     *
     * @return the value of sys_group.group_name
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.group_name
     *
     * @param groupName the value for sys_group.group_name
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.group_type_id
     *
     * @return the value of sys_group.group_type_id
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public Long getGroupTypeId() {
        return groupTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.group_type_id
     *
     * @param groupTypeId the value for sys_group.group_type_id
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setGroupTypeId(Long groupTypeId) {
        this.groupTypeId = groupTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.parent_id
     *
     * @return the value of sys_group.parent_id
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.parent_id
     *
     * @param parentId the value for sys_group.parent_id
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.create_time
     *
     * @return the value of sys_group.create_time
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.create_time
     *
     * @param createTime the value for sys_group.create_time
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.update_time
     *
     * @return the value of sys_group.update_time
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.update_time
     *
     * @param updateTime the value for sys_group.update_time
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.remark
     *
     * @return the value of sys_group.remark
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.remark
     *
     * @param remark the value for sys_group.remark
     *
     * @mbg.generated Wed May 15 15:21:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}