package com.test.auth.entity;

import java.util.Date;

public class SysResources {
    /**
     * ID
     */
    private Long id;

    /**
     * 角色ID
     */
    private Long roleId;

    /**
     * 资源ID
     */
    private String resourcesId;

    /**
     * 资源类型0：菜单menu,1按钮button
     */
    private String resourcesType;

    /**
     * 
     */
    private Date createTime;

    /**
     * 
     */
    private Date updateTime;

    /**
     * 记录版本
     */
    private Long recordVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.id
     *
     * @return the value of sys_resources.id
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.id
     *
     * @param id the value for sys_resources.id
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.role_id
     *
     * @return the value of sys_resources.role_id
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.role_id
     *
     * @param roleId the value for sys_resources.role_id
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.resources_id
     *
     * @return the value of sys_resources.resources_id
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public String getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.resources_id
     *
     * @param resourcesId the value for sys_resources.resources_id
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public void setResourcesId(String resourcesId) {
        this.resourcesId = resourcesId == null ? null : resourcesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.resources_type
     *
     * @return the value of sys_resources.resources_type
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public String getResourcesType() {
        return resourcesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.resources_type
     *
     * @param resourcesType the value for sys_resources.resources_type
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public void setResourcesType(String resourcesType) {
        this.resourcesType = resourcesType == null ? null : resourcesType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.create_time
     *
     * @return the value of sys_resources.create_time
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.create_time
     *
     * @param createTime the value for sys_resources.create_time
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.update_time
     *
     * @return the value of sys_resources.update_time
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.update_time
     *
     * @param updateTime the value for sys_resources.update_time
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.record_version
     *
     * @return the value of sys_resources.record_version
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public Long getRecordVersion() {
        return recordVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.record_version
     *
     * @param recordVersion the value for sys_resources.record_version
     *
     * @mbg.generated Wed May 15 13:53:17 CST 2019
     */
    public void setRecordVersion(Long recordVersion) {
        this.recordVersion = recordVersion;
    }
}