spring:
  redis:
    database: 2
    host: 111.230.52.145
    port: 6379
    password: chen226
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # 认证中心
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #UPMS 模块
        - id: client-test
          uri: lb://client-test
          predicates:
            - Path=/client/**
          filters:
            # 限流配置
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
              # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
security:
  encode:
      # 前端密码密钥，必须16位
    key: 'thisDemo2ChenHJ!'

# 不校验验证码终端
ignore:
  clients:
    - test
auth:
  login: '/oauth/login'
  userinfo: '/oauth/login'

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:5505/eureka/
    fetchRegistry: false
    instance:
        # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
        prefer-ip-address: true
