package com.test.auth.repository;

import com.test.auth.entity.OauthClientDetails;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface OauthClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    int insert(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    int insertSelective(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    OauthClientDetails selectByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    int updateByPrimaryKeySelective(@Param("record") OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    int updateByPrimaryKey(@Param("record") OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    OauthClientDetails selectOne(@Param("record") OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    List<OauthClientDetails> selectList(@Param("record") OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    List<OauthClientDetails> selectPage(@Param("record") OauthClientDetails record, @Param("pageable") Pageable pageable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Mon May 13 14:53:42 CST 2019
     */
    int updateByPrimaryKeySelectiveLock(@Param("record") OauthClientDetails record);
}