package com.test.auth.repository;

import com.test.auth.entity.SysRole;
import com.test.auth.entity.SysUser;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    SysRole selectByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    int updateByPrimaryKeySelective(@Param("record") SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    int updateByPrimaryKey(@Param("record") SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    SysRole selectOne(@Param("record") SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    List<SysRole> selectList(@Param("record") SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    List<SysRole> selectPage(@Param("record") SysRole record, @Param("pageable") Pageable pageable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed May 15 13:57:13 CST 2019
     */
    int updateByPrimaryKeySelectiveLock(@Param("record") SysRole record);
    List<SysRole> findRoleByUserId(Long userId);
}