package com.test.auth.repository;

import com.test.auth.entity.SysUser;
import com.test.auth.vo.SysUserVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;

import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    SysUser selectByPrimaryKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    int updateByPrimaryKeySelective(@Param("record") SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    int updateByPrimaryKey(@Param("record") SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    SysUser selectOne(@Param("record") SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    List<SysUser> selectList(@Param("record") SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    List<SysUser> selectPage(@Param("record") SysUser record, @Param("pageable") Pageable pageable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Mon May 13 15:28:23 CST 2019
     */
    int updateByPrimaryKeySelectiveLock(@Param("record") SysUser record);

    SysUser findUserByUserName(String username);
}